apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-node
spec:
  serviceName: "hadoop-node"
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-node
  template:
    metadata:
      labels:
        app: hadoop-node
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - hadoop-node
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hadoop-node
        image: cclient/hadoop:2.8.3-datanode
#        imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: ssh
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-node
  labels:
    app: hadoop-node
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22    
  - name: "8040"
    port: 8040
    targetPort: 8040
  - name: "8042"
    port: 8042
    targetPort: 8042
  - name: "50010 "
    port: 50010 
    targetPort: 50010 
  - name: "50020"
    port: 50020
    targetPort: 50020
  - name: "50075"
    port: 50075
    targetPort: 50075
  selector:
    app: hadoop-node